### ISSUE TITLE
Books of Bible List

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-box3/book-package#2]
We need one more top level component that that lists out each book of the Bible. This would probably be the meta element that would be used as a visual method of selecting a book.

Each book name should be clickable, revealing underneath it the Book Package contents.

**Comment by mandolyte** [comment]
@jag3773  Questions:

1. This appears to be a per-book approach. As such, it would not do a rollup of multiple books. Is this correct? Actually, I think a rollup would be quite hard, since the contents of the package would change with every book they clicked. If a rollup is needed, then I suggest a two step approach, pick the books to be included, then let it do the work. This might use either the stepper [MUI](https://material-ui.com/components/steppers/)  or [tabs](https://material-ui.com/components/tabs/).

2. This would not have a way to select specific chapters within a book; just the whole book. Correct?

**Comment by jag3773** [comment]
See https://github.com/unfoldingWord/book-package-app/issues/2
