### ISSUE TITLE
Allow Multiple Books

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-box3/book-package#21]
Similar to allow a range of chapters can be provided, it would be excellent if we could provide a range of books.

For example, if I want to see what is included in Titus, Luke, and Acts, it would be great to be able to specify:

```
<BookPackageRollup bookId='tit,luk,act' chapter='' />
```

and then get the combined numbers for all of those.

**Comment by mandolyte** [comment]
If this was done by showing _from the rollup only_ a set of components for each book, that would be pretty easy. This is because, I do this by only changing the rollup component.

If you want each resource component to be able to loop thru the book list, that require a lot more effort.

And if there is a list of books to process, then there cannot be a list of chapters as well.

Thoughts?

**Comment by jag3773** [comment]
I suppose the bigger picture is that somehow we need to have the de-duplicated word counts for all the resources across a specified list of books.

For example, if a team chooses to do Titus first and then Luke after that, how many articles from Translation Words and how many modules from Translation Academy would be a part of the Luke package, given that they've already translated a handful in the Titus package?

**Comment by mandolyte** [comment]
@jag3773 I will close this based on completion of the current multiple book support. Our chat discussion didn't cover deduped counts of UTW and UTA documents (as opposed to word counts).

I will open another issue and paste your example comment above into it.
