### ISSUE TITLE
Book Package Details

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord-box3/book-package#39]
## BP Information

Re-flow the BP information using the following as an example, using 1 and 2 John.  I'm thinking of something like Tree View https://material-ui.com/components/tree-view/.  Note the order of the resources below too.

---

## > Book Packages Total Word Count: **72,932**

When expanded, it would reveal these *indented*:

### ⌄ Book Packages Subtotals       (<- expanded by default)

* ULT Word Count: **3,245**
* UST Word Count: **4,821**
* UTA Word Count: **10,031**
* UTW Word Count: **2,426**
* UTN Word Count: **33,783**
* UTQ Word Count: **19,088**

### > 2 John Book Package Word Count: **20,668**

When those are expanded, they would reveal each component (*indented*), which would also be a dropdown.  I've expanded them in the example below so I don't have to repeat them twice.

#### ⌄ ULT Word Count: **319**

[Word Frequency Table]

#### ⌄ UST Word Count: **498**

[Word Frequency Table]

#### ⌄ Translation Academy Word Count: **7,373**

*Linked modules: **7 unique**, 14 total links*
[Table of links]

#### ⌄ Translation Words Word Count: **11,254**

*Linked articles: **37 unique**, 69 total links*
[Table of links]

#### ⌄ Translation Notes Word Count: **936**

*Number of Notes: **33***
[Word Frequency Table]

#### ⌄ Translation Questions Word Count: **11,254**

*Number of Questions: **11***
[Word Frequency Table]

**Comment by mandolyte** [comment]
@jag3773 This was copied from issue 8 in book package app project.

**Comment by mandolyte** [comment]
Question 1: wondering whether we should use resource acronyms for all instead of for just ULT,UST?

(answered on zulip... yes, do use acronyms)

**Comment by mandolyte** [comment]
Question 2: the RCL supports restrictions to specified chapters, but this is not noted in the new output design. Should it be?

**Comment by mandolyte** [comment]
Answer 2: since the app doesn't support chapter restrictions and no one has asked for it, just leave it out for now.

Since the only way to input chapters is in the styleguidest UI, we can assume they know if they supplied a restriction or not.

**Comment by jag3773** [comment]
Good work! After first implementation here are a few more tweaks:

* [x] Set the MuiTypography level on the top level items.  Starting at H3 yields the right look and feel, but maybe we should start at H2 and adjust the CSS?  Here is an example:
![Screen Shot 2020-03-06 at 3 14 24 PM](https://user-images.githubusercontent.com/107731/76119372-4471fc80-5fbd-11ea-83c0-b81462e1d1f7.png)

* [x] Referencing the above image, I don't like the double click to reveal "Details" under "ULT Word Count: 319".  Can you make it so that when I click "ULT Word Count: 319" I get the table directly?
* [x] Some things still need formatted (bold, italics) as indicated in the original post, e.g. the drop down under UTA Word Count.
* [x] The listing under Book Packages Subtotals should not haave "total" in them, but rather "ULT Word Count: **2,933**" as in the original post.  Can these be a bulleted list?  This should be MuiTypography-body1 also, so that the font is a bit larger.

**Comment by mandolyte** [comment]
@jag3773 have completed everything but the typography changes. I looked briefly at https://material-ui.com/api/tree-item/#css but do not yet see how to get it done. It will take some study I guess.

At any rate, I'll start that tomorrow.
